"""initial schema

Revision ID: 1fea5b89554e
Revises: 
Create Date: 2026-04-15 03:16:33.928071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fea5b89554e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('task_ids', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('category_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duration_calibration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('llm_estimate', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('waiting_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('touched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('llm_raw_response', sa.Text(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('was_corrected', sa.Integer(), nullable=False),
    sa.Column('postponed_count', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Integer(), nullable=False),
    sa.CheckConstraint(
        "urgency IN ('critique','haute','normale','basse') OR urgency IS NULL",
        name="ck_tasks_urgency",
    ),
    sa.CheckConstraint(
        "status IN ('open','doing','waiting','done','cancelled')",
        name="ck_tasks_status",
    ),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_context', ['context_id'], unique=False)
        batch_op.create_index('idx_tasks_due', ['due_date'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_touched', ['touched_at'], unique=False)

    op.create_table('corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('task_title', sa.Text(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index('idx_corrections_recent', ['corrected_at'], unique=False)

    op.create_table('pending_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # FTS5 virtual table (external-content) for full-text search
    op.execute(
        "CREATE VIRTUAL TABLE tasks_fts USING fts5("
        "title, description, content=tasks, content_rowid=id"
        ")"
    )
    # Triggers to keep FTS5 in sync with tasks table
    op.execute("""
CREATE TRIGGER tasks_ai AFTER INSERT ON tasks BEGIN
  INSERT INTO tasks_fts(rowid, title, description)
  VALUES (new.id, new.title, new.description);
END
""")
    op.execute("""
CREATE TRIGGER tasks_ad AFTER DELETE ON tasks BEGIN
  INSERT INTO tasks_fts(tasks_fts, rowid, title, description)
  VALUES ('delete', old.id, old.title, old.description);
END
""")
    op.execute("""
CREATE TRIGGER tasks_au AFTER UPDATE ON tasks BEGIN
  INSERT INTO tasks_fts(tasks_fts, rowid, title, description)
  VALUES ('delete', old.id, old.title, old.description);
  INSERT INTO tasks_fts(rowid, title, description)
  VALUES (new.id, new.title, new.description);
END
""")

    # Trigger to update touched_at on any UPDATE (covers raw SQL + ORM)
    op.execute("""
CREATE TRIGGER tasks_touched_at AFTER UPDATE ON tasks
FOR EACH ROW WHEN NEW.touched_at IS OLD.touched_at BEGIN
  UPDATE tasks SET touched_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END
""")

    # Archive table — explicit schema so constraints and PK are preserved
    op.execute("""
CREATE TABLE tasks_archive (
  id INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  context_id INTEGER,
  urgency TEXT,
  due_date DATE,
  estimated_minutes INTEGER,
  actual_minutes INTEGER,
  tags TEXT,
  status TEXT NOT NULL,
  waiting_reason TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  touched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  llm_raw_response TEXT,
  llm_confidence REAL,
  llm_reasoning TEXT,
  was_corrected INTEGER NOT NULL DEFAULT 0,
  postponed_count INTEGER NOT NULL DEFAULT 0,
  needs_review INTEGER NOT NULL DEFAULT 0,
  archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS tasks_archive")
    op.execute("DROP TRIGGER IF EXISTS tasks_touched_at")
    op.execute("DROP TRIGGER IF EXISTS tasks_au")
    op.execute("DROP TRIGGER IF EXISTS tasks_ad")
    op.execute("DROP TRIGGER IF EXISTS tasks_ai")
    op.execute("DROP TABLE IF EXISTS tasks_fts")
    op.drop_table('pending_prompts')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index('idx_corrections_recent')

    op.drop_table('corrections')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_touched')
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_due')
        batch_op.drop_index('idx_tasks_context')

    op.drop_table('tasks')
    op.drop_table('duration_calibration')
    op.drop_table('category_notes')
    op.drop_table('settings')
    op.drop_table('goals')
    op.drop_table('digests')
    op.drop_table('contexts')
    op.drop_table('categories')
    # ### end Alembic commands ###
